---

- hosts: all
  become: yes

  ##################
  # clone git repo #
  #################
  tasks:
  - name: clone -> goVaultYourselfAgain
    git:
      # repo: git@github.com:svendavison/goVaultYourselfAgain.git
      repo: https://svendavison:{{ github_password }}@github.com/svendavison/goVaultYourselfAgain.git
      dest: /opt/goVaultYourselfAgain
    tags:
    - clonerepo

  ###########################
  # Copy dir to remote host #
  ###########################
  - name: Copy local ./sampledir/ to /opt/zomg on target
    copy:
      src: ./sampledir/
      dest: /opt/zomg
    tags:
    - copyzomg

  
  #################################
  # user creation stuff via roles #  
  #################################

  vars_files:
    - enc-data.yml
  roles:
    - weareinteractive.users
  vars:
    users:
      - username: sdavison
        name: Sven Davison
        home_create: yes
        groups:
          - users
          - wheel
        append: yes
        home_mode: "0750"
        authorized_keys:
          # - "{{ lookup('file', 'tests/id_rsa.pub') }}"
          - "{{ common_authorized_keys }}"
          - "{{ vault_ansible_2020_rsa_pub }}"
        ssh_keys:
          # id_rsa: "{{ lookup('file', 'tests/ansible-2020_rsa') }}"
          id_rsa: "{{ ansible_2020_rsa }}"
          laptop_rsa: "{{ laptop_rsa }}"
        # ssh_key_generate: yes
        # ssh_key_password: secret
      - username: benspelledabc
        home_create: yes
        groups:
          - users
        append: yes
        home_mode: "0750"
        authorized_keys:
          - "{{ vault_ansible_2020_rsa_pub }}"
        ssh_keys:
          id_rsa: "{{ ansible_2020_rsa }}"

    users_group: staff
    users_groups:
      - www-data
      - unicorns
    users_authorized_keys_exclusive: yes
    users_remove:
      # - { username: foobar, remove: yes }
      # - { username: foobar_key, remove: yes }
      # - { username: foobar_keys, remove: yes }
      # - { username: foobar_authorized_keys, remove: yes }
      # - { username: foobar_file, remove: yes }
      # - { username: foobar_groups, remove: yes }
      # - { username: foobar_groups_reset, remove: yes }
      # - { username: foobar_home_mode, remove: yes }
      # - { username: foobar_key_generate, remove: yes }
      # - { username: foobar_system, remove: yes }
